
BASIC_ROSE_HP = 50
--IEnemyable
data.EnemyConfig = {
    -- dict: [tileId : EnemyConfigLol]
    [32] = {
        name = 'MusicAutoBulletHell',
        circleDiameter = 5,
        bulletSpreadRadius = 5,
        bulletRotationSpeed = 0.001,
        bulletCount = 8,
        bulletSpeed = 0.8,
        deathBulletSpeed = 0.3,
        color = 13,
        music = drums[48],
        hp = 12,
        autoAim = true,
    },
    [33] = {
        name = 'BulletHell',
        circleDiameter = 8,
        bulletSpreadRadius = 8,
        bulletRotationSpeed = 1,
        bulletCount = 12,
        bulletSpeed = 0.7,
        deathBulletSpeed = 0.2,
        color = 13,
        hp = 25,
        autoAim = true,
    },
    [34] = {
        name = 'BulletHell',
        circleDiameter = 16,
        bulletSpreadRadius = 11,
        bulletRotationSpeed = 1,
        bulletCount = 16,
        bulletSpeed = 0.8,
        deathBulletSpeed = 0.1,
        color = 13,
        hp = 50,
        autoAim = true,
    },
    [48] = {
        name = 'MusicBulletHell',
        circleDiameter = 5,
        bulletSpreadRadius = 5,
        -- bulletRotationSpeed = 0.001,
        bulletRotationSpeed = 0.002,
        bulletCount = 8,
        bulletSpeed = 1.1,
        deathBulletSpeed = 0.1,
        color = 14,
        music = drums[48],
        hp = 16,
    },
    [49] = {
        name = 'MusicBulletHell',
        circleDiameter = 8,
        bulletSpreadRadius = 8,
        -- bulletRotationSpeed = 0.001,
        bulletRotationSpeed = 0.0009,
        bulletCount = 12,
        bulletSpeed = 0.7,
        deathBulletSpeed = 0.1,
        color = 14,
        music = drums[49],
        hp = 36,
    },
    -- [49] = {
    --     name = 'BulletHell',
    --     circleDiameter = 8,
    --     bulletSpreadRadius = 8,
    --     bulletRotationSpeed = 1,
    --     bulletCount = 12,
    --     bulletSpeed = 0.7,
    --     deathBulletSpeed = 0.2,
    --     color = 14,
    --     hp = 25,
    -- }, -- bullet help pls
    [50] = {
        name = 'BulletHell',
        circleDiameter = 16,
        bulletSpreadRadius = 11,
        bulletRotationSpeed = 1,
        bulletCount = 16,
        bulletSpeed = 0.8,
        deathBulletSpeed = 0.1,
        color = 14,
        hp = 40,
    },
    [65] = {
        name = 'Snowman',
        color = 12,
        speed = 12, -- data.Player.speed - 0.41,
        speedWithWhirl = 0.8, --data.Player.speed - 0.61,
        hp = 100,
        prepareJumpTime = 20,
        --jumpTime = 20,
        resetJumpTime = 24,

        deathParticleCountMin = 100,
        deathParticleCountMax = 300,
        deathAnimationParticleSpeed = 1,
        deathAnimationParticleSpeedNormalizer = 0.4,
        deathParticleMinSpeed = 1,
        deathParticleSprite = Sprite:new({378}, 1),

        specialTaraxacum = {
            radius = 3,
            bodyLength = 15,
            shiftForCenterX = 12,
            shiftForCenterY = -3,
            startStickX = 0,
            startStickY = 0,
            bodyColor = 10,
            color = 12,
            reloadAnimationTime = 18, -- in tics should divide by 3
        },

        music = {
            beatMap = {0, 0, 1, 1, 1, 1},
            sfxMap = bassLine.rose.D2.sfxMap,
        },

        sprites = {
            chill = Sprite:new({312}, 2),
            prepareJump = Sprite:new({312, 344}, 2),
            flyJump = Sprite:new(anim.gen60({346,348,346}), 2),
            resetJump = Sprite:new({348,344,312}, 2),
            death = Sprite:new(anim.gen60({312,314,312,314,312}), 2)
        },
    },
    [97] = {
        name = 'StaticTaraxacum',
        speed = 2,
        color = 12,

        radius = 2,
        staticRadius = 3,
        bodyLength = 10,
        staticTaraxacumSpawnTile = { 97 },

        deathBulletCount = 6,
        deathBulletSlowCount = 3,
        deathBulletFastCount = 3,

        deathBulletSpeed = 0.37,
        deathSlowBulletSpeed = 0.2,
        deathFastBulletSpeed = 0.5,

        deathBulletSpread = 2,

        deathBulletSprite = Sprite:new({378}, 1),
    }, -- mb static idk
    [98] = {
        name = 'Enemy',
    },
    [150] = {},
    [151] = {},
    [152] = {},
    [153] = {},

    [166] = {},
    [167] = {},
    [168] = {},
    [169] = {},
    --D2 = {182, 183, 184, 185},
    -- Fd2 = {170, 171, 172, 173},
    -- Gd2 = {186, 187, 188, 190},
    [170] = {
        name = 'MusicRose',
        music = bassLine.rose.Fd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 0,
    },
    [171] = {
        name = 'MusicRose',
        music = bassLine.rose.Fd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 1,
    },
    [172] = {
        name = 'MusicRose',
        music = bassLine.rose.Fd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 2,
    },
    [173] = {
        name = 'MusicRose',
        music = bassLine.rose.Fd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 3,
    },

    [182] = {
        name = 'MusicRose',
        music = bassLine.rose.D2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 0,
    },
    [183] = {
        name = 'MusicRose',
        music = bassLine.rose.D2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 1,
    },
    [184] = {
        name = 'MusicRose',
        music = bassLine.rose.D2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 2,
    },
    [185] = {
        name = 'MusicRose',
        music = bassLine.rose.D2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 3,
    },

    [186] = {
        name = 'MusicRose',
        music = bassLine.rose.Gd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 0,
    },
    [187] = {
        name = 'MusicRose',
        music = bassLine.rose.Gd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 1,
    },
    [188] = {
        name = 'MusicRose',
        music = bassLine.rose.Gd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 2,
    },
    [189] = {
        name = 'MusicRose',
        music = bassLine.rose.Gd2,
        startingHealth = BASIC_ROSE_HP,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 3,
    },
    [198] = {
        name = 'MusicWeakRose',
        music = bassLine.rose.D2,
        startingHealth = 1,
        metronomeTicksReloading = 1,
        metronomeTicksSpentShooting = 1,
        direction = 0,
    },
}
